name: Deploy to VPS

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name : Build website
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
    - uses: limjh16/jekyll-action-ts@v2
      with:
        enable_cache: true
        custom_opts: "-d ./build"

    - name: Copy files to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_IPV4 }} >> ~/.ssh/known_hosts
        rsync -avz --delete ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_IPV4 }}:/var/www/html/